/// Flutter icons EventIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EventIcons
///      fonts:
///       - asset: fonts/EventIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EventIcons {
  EventIcons._();

  static const _kFontFam = 'EventIcons';

  static const IconData man_user = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData admin_message = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData telephone = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData help = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe804, fontFamily: _kFontFam);
}
